/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imageprocessing_ImageProcessor */

#ifndef _Included_imageprocessing_ImageProcessor
#define _Included_imageprocessing_ImageProcessor
#ifdef __cplusplus
extern "C" {
#endif
#undef imageprocessing_ImageProcessor_numBuffers
#define imageprocessing_ImageProcessor_numBuffers 1L
/*
 * Class:     imageprocessing_ImageProcessor
 * Method:    process
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imageprocessing_ImageProcessor_process
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
