/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imageprocessing_ImageUtil */

#ifndef _Included_imageprocessing_ImageUtil
#define _Included_imageprocessing_ImageUtil
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
