/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imageprocessing_ObjectFinder */

#ifndef _Included_imageprocessing_ObjectFinder
#define _Included_imageprocessing_ObjectFinder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imageprocessing_ObjectFinder
 * Method:    getObjectType
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_imageprocessing_ObjectFinder_getObjectType
  (JNIEnv *, jobject, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
