/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class robotparts_Servo */

#ifndef _Included_robotparts_Servo
#define _Included_robotparts_Servo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     robotparts_Servo
 * Method:    setPosition
 * Signature: (JID)V
 */
JNIEXPORT void JNICALL Java_robotparts_Servo_setPosition
  (JNIEnv *, jobject, jlong, jint, jdouble);

#ifdef __cplusplus
}
#endif
#endif
