/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class robotparts_Gyroscope */

#ifndef _Included_robotparts_Gyroscope
#define _Included_robotparts_Gyroscope
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     robotparts_Gyroscope
 * Method:    getHeading
 * Signature: (JJ)D
 */
JNIEXPORT jdouble JNICALL Java_robotparts_Gyroscope_getHeading
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
