/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sensors_UltraSonicSensor */

#ifndef _Included_sensors_UltraSonicSensor
#define _Included_sensors_UltraSonicSensor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sensors_UltraSonicSensor
 * Method:    echoHandle
 * Signature: (JJ)D
 */
JNIEXPORT jdouble JNICALL Java_sensors_UltraSonicSensor_echoHandle
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
