/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sensorIO_Pwm */

#ifndef _Included_sensorIO_Pwm
#define _Included_sensorIO_Pwm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sensorIO_Pwm
 * Method:    init
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_sensorIO_Pwm_init
  (JNIEnv *, jobject, jint);

/*
 * Class:     sensorIO_Pwm
 * Method:    setSpeed
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_sensorIO_Pwm_setSpeed
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     sensorIO_Pwm
 * Method:    getSpeed
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_sensorIO_Pwm_getSpeed
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sensorIO_Pwm
 * Method:    setEnableStatus
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_sensorIO_Pwm_setEnableStatus
  (JNIEnv *, jobject, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
