/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sensorIO_Aio */

#ifndef _Included_sensorIO_Aio
#define _Included_sensorIO_Aio
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sensorIO_Aio
 * Method:    init
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_sensorIO_Aio_init
  (JNIEnv *, jobject, jint);

/*
 * Class:     sensorIO_Aio
 * Method:    read
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_sensorIO_Aio_read
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sensorIO_Aio
 * Method:    setBit
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_sensorIO_Aio_setBit
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     sensorIO_Aio
 * Method:    getBit
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_sensorIO_Aio_getBit
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
