/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sensorIO_Spi */

#ifndef _Included_sensorIO_Spi
#define _Included_sensorIO_Spi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sensorIO_Spi
 * Method:    init
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_sensorIO_Spi_init
  (JNIEnv *, jobject, jint);

/*
 * Class:     sensorIO_Spi
 * Method:    write
 * Signature: (JC)C
 */
JNIEXPORT jchar JNICALL Java_sensorIO_Spi_write__JC
  (JNIEnv *, jobject, jlong, jchar);

/*
 * Class:     sensorIO_Spi
 * Method:    write
 * Signature: (JCI)C
 */
JNIEXPORT jchar JNICALL Java_sensorIO_Spi_write__JCI
  (JNIEnv *, jobject, jlong, jchar, jint);

/*
 * Class:     sensorIO_Spi
 * Method:    bitPerWord
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_sensorIO_Spi_bitPerWord
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
