/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sensorIO_Shield */

#ifndef _Included_sensorIO_Shield
#define _Included_sensorIO_Shield
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sensorIO_Shield
 * Method:    init
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_sensorIO_Shield_init
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
